Repository upex-galaxy/upex-cypress-demo, pull requests merged in 2024-10, with the labels that each got.

#711 Test/gx2 24086/crear obtener eliminar usuario
  .github/workflows/sanityJanetzi.yml
  cypress/e2e/Tests/BookStore/GX2-24086-crear-obtener-eliminar-usuario.cy.js
  cypress/support/pages/GX2-24086-crear-obtener-eliminar-usuario.Page.js
Labels: Needs Review, Tutor Assigned

#710 Test/GX3-4979/droppable
  coverage/S45/GX3-4979.md
  cypress/e2e/Tests/Interactions/GX3-4979-droppable.cy.ts
  cypress/support/pages/GX3-4979-droppable.Page.ts
Labels: Needs Review

#713 Test/gx2 24966/actualizar eliminar libros
  cypress/e2e/Tests/BookStore/GX2-24966-actualizar-eliminar-libros.cy.js
  cypress/support/pages/GX2-24966-actualizar-eliminar-libros.Page.js
Labels: Needs Review

#714 Gx3 5270 tools qa elements radio buttons
  coverage/S47/GX3-5270.md
  cypress/e2e/Tests/Elements/GX3-5270_Radio-Button.cy.js
Labels: Needs Review, Tutor Assigned

#716 test: (GX3-5305) Added 3 test cases to the Buttons page
  coverage/S47/GX3-5305.md
  cypress/e2e/Tests/Elements/GX3-5305-Buttons.cy.js
Labels: Tutor Assigned

#718 Gx3 5337 tools qa elements buttons
  coverage/S47/GX3-5337.md
  cypress/e2e/Tests/Elements/GX3-5337-Buttons.cy.js
Labels: Approved, Tutor Assigned

#719 test: (GX3-5360) Added 12 test cases to the Check Box page
  coverage/S47/GX3-5360.md
  cypress/e2e/Tests/Elements/GX3-5360-Checkbox.cy.js
Labels: Approved, Tutor Assigned

#722 test: (GX3-5443) Prueba automatizada para Radio-buttons
  coverage/S47/GX3-5443.md
  cypress/e2e/Tests/Elements/GX3-5443-Radio-Buttons.cy.js
Labels: Needs Review

#720 Gx3 5370 tools qa elements text box fill form and submit
  coverage/S47/GX3-5337.md
  coverage/S47/GX3-5370.md
  cypress/e2e/Tests/Elements/GX3-5337-Buttons.cy.js
  cypress/e2e/Tests/Elements/GX3-5370-TextBox.cy.js
  cypress/fixtures/data/Elements/GX3-5370_CredentialTextBox.json
Labels: Approved, Tutor Assigned

#721 Test: (GX3-5409) Added 3 test cases to the Upload and Download page
  coverage/S47/GX3-5409.md
  cypress/e2e/Tests/Elements/GX3-5409-upload-download.cy.js
Labels: Approved, Tutor Assigned

#723 Test: (GX3-5422) Added 6 test cases to the Select Menu page
  coverage/S47/GX3-5360.md
  coverage/S47/GX3-5422.md
  cypress/e2e/Tests/Elements/GX3-5360-Checkbox.cy.js
  cypress/e2e/Tests/Widgets/GX3-5422.cy.js
Labels: Approved, Tutor Assigned

#724 Gx3 5427 tools qa elements checkbox
  coverage/S47/GX3-5370.md
  coverage/S47/GX3-5427.md
  cypress/e2e/Tests/Elements/GX3-5370-TextBox.cy.js
  cypress/e2e/Tests/Elements/GX3-5427-Check_Box.cy.js
  cypress/fixtures/data/Elements/GX3-5370_CredentialTextBox.json
Labels: Approved, Tutor Assigned

#725 Gx3 5376 ⚡️ tools qa interactions selectable
  coverage/S47/GX3-5376.md
  cypress/e2e/Tests/Interactions/GX3-5376-Selectable.cy.js
  cypress/support/pages/GX3-5376-Selectable.Page.js
Labels: Needs Review
