Repository upex-galaxy/upex-cypress-demo, pull requests merged in 2024-08, with the labels that each got.

#698 Gx3 4358 tools qa widgets dropdown select menu
  .github/workflows/sanityJanetziJackiewicz.yml
  coverage/S44/GX3-4358.md
  cypress/e2e/Tests/Widgets/GX3-4358-SelectMenu.cy.ts
  cypress/support/pages/GX3-4358-SelectMenu.Page.ts
Labels: Needs Review, Tutor Assigned

#695 Gx3 4620 ⚡️ tools qa elements radio buttons
  .github/workflows/regression.yml
  .github/workflows/sanityDonnaCas.yml
  .github/workflows/sanityTest.yml
  .github/workflows/tutorial.yml
  coverage/S45/GX3-4620.md
  cypress/e2e/Tests/Elements/GX3-4620-Radio-Buttons.cy.js
  yarn.lock
Labels: Requirements Not Met, Minor Tweaks Needed

#699 test (GX3-4687): nueva prueba automatizada para radio button
  .github/workflows/sanityJeselySuarez.yml
  coverage/S45/GX3-4687.md
  cypress/e2e/Tests/Elements/GX3-4687_radioButton.cy.js
Labels: Needs Review, Minor Tweaks Needed

#702 test: (GX3-4799) Three test cases are added to verify the functionali…
  coverage/S45/GX3-4799.md
  cypress/e2e/Tests/Elements/GX3-4799-Buttons.cy.js
Labels: Needs Review

#703 Gx3 4847 tools qa elements buttons
  coverage/S45/GX3-4847.md
  cypress/e2e/Tests/Elements/GX3-4847_elementsButtons.cy.js
Labels: Needs Review, Tutor Assigned

#704 Gx3 4933 tools qa elements text box fill form and submit
  coverage/S45/GX3-4933.md
  cypress/e2e/Tests/Elements/GX3-4933_textBox.cy.js
  cypress/fixtures/data/Elements/GX3-4933_textBox.json
Labels: Needs Review, Tutor Assigned

#707 test: (GX3-4941) Six test cases are added to verify the Sortable List and Grid functionality
  coverage/S45/GX3-4941.md
  cypress/e2e/Tests/Interactions/GX3-4941-sortable.cy.js
Labels: Needs Review
