Repository upex-galaxy/upex-cypress-demo, pull requests merged in 2024-06, with the labels that each got.

#663 Gx3 303 tools qa widgets dropdown select menu
  .github/workflows/sanityLilianaProspel.yml
  coverage/S40/GX3-3030.md
  cypress/e2e/Tests/Widgets/GX3-3030-SelectMenu.cy.js
  cypress/fixtures/data/Widgets/GX3-3030-SelectMenu.json
  cypress/support/pages/GX3-3030-SelectMenu.Page.js
Labels: Approved

#665 GX3-3014 forms-practice-form
  .github/workflows/sanityAlexWindecker.yml
  coverage/S40/GX3-3014.md
  cypress/e2e/Tests/Interactions/GX3-3014-FormPractice.cy.js
  cypress/support/pages/GX3-2449-PracticeForm.Page.js
  cypress/support/pages/GX3-3014-FormsPractice.Page.js
Labels: Needs Review

#668 GX3-3241-demoqa-elements-checkbox
  .github/workflows/sanityNelaSerodino.yml
  coverage/S41/GX3-3241.md
  cypress/e2e/Tests/Elements/GX3-3241-CheckBox.cy.ts
  cypress/fixtures/data/Elements/GX3-3241-checkbox.json
  cypress/support/pages/GX3-3241-Checkbox.page.ts
Labels: Approved, Tutor Assigned

#675 GX3-3659 tools qa elements radio buttons
  .github/workflows/sanityMarlovxEsquivel.yml
  coverage/S43/GX3-3659.md
  cypress/e2e/Tests/Elements/GX3-3659-radioButtons.cy.js
Labels: Needs Review

#674 Gx3 3651 tools qa elements buttons
  .github/workflows/sanityMiriamHonorio.yml
  coverage/S43/GX3-3651.md
  cypress/e2e/Tests/Elements/GX3-3651-Buttons.cy.js
Labels: Needs Review, Tutor Assigned

#678 GX3-3778 tools qa elements buttons
  .github/workflows/sanityMarlovxEsquivel.yml
  coverage/S43/GX3-3778.md
  cypress/e2e/Tests/Elements/GX3-3778-elementsButtons.cy.js
Labels: Needs Review

#679 Gx3 3754 tools qa elements text box fill form and submit
  .github/workflows/sanityMiriamHonorio.yml
  coverage/S43/GX3-3754.md
  cypress/e2e/Tests/Elements/GX3-3754-TexBox.cy.js
  cypress/fixtures/data/Elements/GX3-3754-TextBox.json
Labels: Needs Review, Tutor Assigned

#680 Gx3 3810 tools qa elements dynamic properties
  .github/workflows/sanityMiriamHonorio.yml
  coverage/S43/GX3-3810.md
  cypress/e2e/Tests/Elements/GX3-3810-dynamicProperties.cy.js
Labels: Needs Review, Tutor Assigned

#681 Gx3 3875 tools qa elements upload and download
  .github/workflows/sanityMiriamHonorio.yml
  coverage/S43/GX3-3875.md
  cypress/e2e/Tests/Elements/GX3-3875-uploadDownload.cy.js
  cypress/support/pages/GX3-3875-uploadDownload.page.js
Labels: Needs Review, Tutor Assigned

#673 Gx3 3682 tools qa elements buttons
  .github/workflows/sanityPabloCarrizo.yml
  coverage/S43/GX3-3682.md
  cypress/e2e/Tests/Elements/GX3-3682-button.cy.js
Labels: Needs Review
