Repository upex-galaxy/upex-cypress-demo, pull requests merged in 2024-11, with the labels that each got.

#728 Gx3 5504 tools qa widgets dropdown select menu
  coverage/S47/GX3-5504.md
  cypress/e2e/Tests/Widgets/GX3-5504-Dropdown.cy.js
Labels: Approved, Tutor Assigned

#726 test: (GX3-5457) Added 10 test cases to the Date Picker Page
  coverage/S47/GX3-5457.md
  cypress/e2e/Tests/Widgets/GX3-5457-DatePicker.cy.js
  cypress/support/pages/GX3-5457-DatePicker.page.js
Labels: Needs Review, Tutor Assigned

#729 Test (GX3-5484): ToolsQA | Elements | Text Box: Fill form and Submit
  .github/workflows/sanity-verogeid.yml
  coverage/S48/GX3-5484.md
  cypress/e2e/Tests/Elements/GX3-5484_TextBox-FillFormAndSubmit.cy.js
  cypress/fixtures/data/Elements/GX3-5484_TextBox-FillFormAndSubmit.json
Labels: In Review

#730 Test (GX3-5552): ToolsQA | Elements | Radio Buttons
  .github/workflows/sanity-verogeid.yml
  coverage/S48/GX3-5552.md
  cypress/e2e/Tests/Elements/GX3-5552-Radio-Buttons.cy.js
Labels: Approved
